apiVersion: v1
kind: Service
metadata:
  name: {{ include "fast-api-ai.fullname" . }}
spec:
  selector:
    app: {{ include "fast-api-ai.name" . }}
  ports:
    - protocol: TCP
      port: {{ .Values.service.port }}       # 80
      targetPort: {{ .Values.service.targetPort }} # 8000
  type: {{ .Values.service.type }}