server:
  port: 8000

eureka:
  client:
    tls:
      enabled: false
      #trust-all-certs: true
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: https://eureka.sj-lab.co.kr/eureka
      #defaultZone: http://www.sj-lab.co.kr/discovery/eureka
  instance:
    prefer-ip-address: true
    instance-id: ${spring.application.name}:${spring.cloud.client.hostname}
    lease-renewal-interval-in-seconds: 10
    lease-expiration-duration-in-seconds: 30
    #instance-id: ${spring.application.name}:${spring.application.instance_id:${random.value}}
    #prefer-ip-address: true

swagger:
  docs_url: "/api/ai/v1/docs"
  openapi_url: "/api/ai/v1/openapi.json"